### ISSUE TITLE
Any chance of updating AXN/MLC to support LXD containers also?

### ISSUE THREAD

**Issue by bmullan** [axn/mlc#4]
LXD containers are from the same developer group that does LXC but LXD containers offer many advantages over the earlier LXC (non-LXD).

https://linuxcontainers.org/#LXD

**Comment by axn** [comment]
I do not have time to work on lxd support any time soon. But feel free to send respective patches. 
/axel

Am 11. November 2019 00:50:03 MEZ schrieb brian mullan <notifications@github.com>:
>LXD containers are from the same developer group that does LXC but LXD
>containers offer many advantages over the earlier LXC (non-LXD).
>
>https://linuxcontainers.org/#LXD
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/axn/mlc/issues/4

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by bmullan** [comment]
If I was a programmer I would.  But thanks for the reply.
brian
